services:
  db:
    image: postgres:alpine
    container_name: petshop_db
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data # Persists data to a named volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: